### ISSUE TITLE
Code dùng os.system, để execute 1 command như vcftool, hisat2 ...

### ISSUE THREAD

**Issue by linuxpham** [kspham/rnavariantcalling#1]
Hi Tân,
Code pipeline dùng os.system để execute 1 external command có 2 vấn đề :
- ko security vì chưa escape shell command
- ko handle được trạng thái của external command
  Anh suggestion dùng thêm 2 hàm này :
  ## 1/ execute a command
  
  def executeCommand(sCommand):  
      ###Get all output data
      outData, errData = subprocess.Popen(sCommand, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, close_fds=True).communicate()
  
  ```
  ###Get all response data
  for lineData in outData.splitlines():
      if(self.RUNNING_DEBUG_FLAG == 1):
          outStringData = str(lineData)
          print("%s" % (outStringData))
  
  ###If there is error
  if((errData != None) and (len(errData) > 0)):
      print("Command has error:{0}".format(errData))
  ```
  ---
## 2/ escape shell script

def shellEscape(s):
##        return s.replace("(","\(").replace(")","\)")

Thanks !!!

**Comment by ptdtan** [comment]
Thanks anh,

Em sẽ thêm vào ngay.

Em cần push reference sequence đã indexed lên Github nhưng mà dung lượng
lớn quá thì phải làm sao anh, vì thời gian index lâu nên nếu mình index
trước thì sẽ tiết kiệm được nhiều thời gian. Anh giúp em cái này với.

On Fri, Nov 27, 2015 at 4:30 PM, Son Pham notifications@github.com wrote:

> Assigned #1 https://github.com/kspham/rnavariantcalling/issues/1 to
> @ptdtan https://github.com/ptdtan.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kspham/rnavariantcalling/issues/1#event-476163460.

## 

[image: School of Biotechonology, University of Science, VN]
http://t.sidekickopen30.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XX48r4QZ8VRs1WF4XrfFzW2BW4zb56dSjmf3Z1Lz802?t=https%3A%2F%2Fhtmlsig.com%2Fsignatures%2F001AVRV8R&si=4754681951158272&pi=398d7ec0-1e7b-4565-80ab-0a54bf5b68b3

Phan Thai Duy Tan / Senior
ptdtan@gmail.com / +841647970094

School of Biotechnology, University of Science, VN
227 Nguyen Van Cu St District 5

[image: Facebook] http://facebook.com/alan.phan21

**Comment by linuxpham** [comment]
Hi Tan,
Em viet cai shell script :
- Tu dong download cai reference fasta ve (reference fasta em chon tu nguon tin cay, co the nho Dr SON tu van chon nguon nhe)
- Tu dong create index file
  Sau do em note len tren README, anh dung tao index file lai em nhe.
  Thanks !!!

**Comment by ptdtan** [comment]
Hi anh Hoa, 

lam sao de su dung ham escap shell command kia vay anh?

Thanks anh.

**Comment by ptdtan** [comment]
ah em da hieu roi, co phai vi security, de chong injection dung khong anh

Thanks anh!

**Comment by ptdtan** [comment]
Hmm, chac em se note tren README link reference sequence recommended cua minh de nguoi dung download ve , roi set mot argument la reference. Roi em se them mot buoc index nua vao pipeline. 

Hoac la minh upload file indexed cua minh len de nguoi dung tai ve de khoi ton time index, anh thay sao anh?

Em thu tim file reference da indexed tren homepage cua STAR ma khong co.

**Comment by ptdtan** [comment]
Hi anh, em da tim duoc link reference da indexed, em se note lai tren README.

Thanks anh!
