### ISSUE TITLE
Log file tao ngay thu muc chay tool

### ISSUE THREAD

**Issue by linuxpham** [kspham/rnavariantcalling#13]
Hi Tan,

hien tai co van de la log files khi chay pipeline tao tu dong tai thu muc hien tai

VD : anh dang thu muc /home/hoa, chay pipeline thi file logs se duoc tao tai day (du git clone vao thu muc rnavariantcalling

![screen shot 2015-12-14 at 20 40 45](https://cloud.githubusercontent.com/assets/154762/11782394/5dbec58c-a2a3-11e5-9a70-1d9c633099c8.png)

Em add them 1 param do add log directory nua nhe.

Thanks !!!

**Comment by ptdtan** [comment]
OK anh, em sua lai roi se bao anh.

Thanks anh.

On Mon, Dec 14, 2015 at 8:43 PM, Pham Thai Hoa notifications@github.com
wrote:

> Hi Tan,
> 
> hien tai co van de la log files khi chay pipeline tao tu dong tai thu muc
> hien tai
> 
> VD : anh dang thu muc /home/hoa, chay pipeline thi file logs se duoc tao
> tai day (du git clone vao thu muc rnavariantcalling
> 
> [image: screen shot 2015-12-14 at 20 40 45]
> https://cloud.githubusercontent.com/assets/154762/11782394/5dbec58c-a2a3-11e5-9a70-1d9c633099c8.png
> 
> Em add them 1 param do add log directory nua nhe.
> 
> Thanks !!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kspham/rnavariantcalling/issues/13.

## 

[image: School of Biotechonology, University of Science, VN]
https://htmlsig.com/signatures/001AVRV8R

Phan Thai Duy Tan / Senior
ptdtan@gmail.com / +841647970094

School of Biotechnology, University of Science, VN
227 Nguyen Van Cu St District 5

[image: Facebook] http://facebook.com/alan.phan21

**Comment by ptdtan** [comment]
Em da commit len anh pull ve chay lai nhe anh.

Thanks anh.
