### ISSUE TITLE
freebayes for rna-seq

### ISSUE THREAD

**Issue by kspham** [kspham/rnavariantcalling#9]
RNA-seq in some areas have very high coverage or very low coverage (very different from DNA). This causes the memory intensive scenario that we observed. 
We should subsample these high coverage regions before moving to freebayes.

**Comment by ptdtan** [comment]
I see. I'm trying to subsample those high coverage regions at the moment

**Comment by ptdtan** [comment]
Could you suggest any efficient method, Son?

**Comment by ptdtan** [comment]
Hmm, an issue which was reported on freebayes repository few days ago state that 1.0.1 version of freebayes cause memory leaking but the older version. I replaced current freebayes version by the older one then the memory problem was resolved.
